平成 28/1/5 18:55:54 にビルドを開始しました。
     1>ノード 2 上のプロジェクト "E:\git\C_py\c-py\c-py\c-py.vcxproj" (Build ターゲット)。
     1>ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /IC:\Python33\include /ZI /nologo /W3 /WX- /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _CONSOLE /D _LIB /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:prompt main.cpp
         main.cpp
     1>c:\python33\include\pymath.h(22): warning C4273: 'round' : dll リンクが一貫していません。
                 c:\program files (x86)\microsoft visual studio 12.0\vc\include\math.h(516) : 'round' の前の定義を確認してください
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"E:\git\C_py\c-py\Debug\c-py.exe" /INCREMENTAL /NOLOGO /LIBPATH:C:\Python33\libs python33.lib python3.lib kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:\git\C_py\c-py\Debug\c-py.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\git\C_py\c-py\Debug\c-py.lib" /MACHINE:X86 Debug\main.obj
     1>main.obj : error LNK2019: 未解決の外部シンボル __imp__PyModule_GetDict が関数 _main で参照されました。
     1>main.obj : error LNK2019: 未解決の外部シンボル __imp__Py_Initialize が関数 _main で参照されました。
     1>main.obj : error LNK2019: 未解決の外部シンボル __imp__Py_Finalize が関数 _main で参照されました。
     1>main.obj : error LNK2019: 未解決の外部シンボル __imp__PyRun_FileExFlags が関数 _main で参照されました。
     1>main.obj : error LNK2019: 未解決の外部シンボル __imp__PyImport_AddModule が関数 _main で参照されました。
     1>E:\git\C_py\c-py\Debug\c-py.exe : fatal error LNK1120: 5 件の未解決の外部参照
     1>プロジェクト "E:\git\C_py\c-py\c-py\c-py.vcxproj" (Build ターゲット) のビルドが終了しました -- 失敗。

ビルドに失敗しました。

経過時間 00:00:00.40
