平成 28/1/5 12:23:04 にビルドを開始しました。
     1>ノード 2 上のプロジェクト "E:\git\C_py\C_py\C_py\C_py.vcxproj" (Build ターゲット)。
     1>ClCompile:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\CL.exe /c /ZI /nologo /W3 /WX- /sdl /Od /Oy- /D WIN32 /D _DEBUG /D _WINDOWS /D _UNICODE /D UNICODE /Gm /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Fo"Debug\\" /Fd"Debug\vc120.pdb" /Gd /TP /analyze- /errorReport:prompt main.cpp
         main.cpp
       Link:
         C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:PROMPT /OUT:"E:\git\C_py\C_py\Debug\C_py.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"E:\git\C_py\C_py\Debug\C_py.pdb" /SUBSYSTEM:WINDOWS /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"E:\git\C_py\C_py\Debug\C_py.lib" /MACHINE:X86 Debug\main.obj
     1>MSVCRTD.lib(crtexew.obj) : error LNK2019: 未解決の外部シンボル _WinMain@16 が関数 ___tmainCRTStartup で参照されました。
     1>E:\git\C_py\C_py\Debug\C_py.exe : fatal error LNK1120: 1 件の未解決の外部参照
     1>プロジェクト "E:\git\C_py\C_py\C_py\C_py.vcxproj" (Build ターゲット) のビルドが終了しました -- 失敗。

ビルドに失敗しました。

経過時間 00:00:00.73
